FROM openjdk:8
LABEL maintainer="naveen.deism@gmail.com"
VOLUME /tmp
EXPOSE 8085
ADD /target/optimize-weight-value-services-service-0.0.1-SNAPSHOT.jar optimize-weight-value-services-service.jar
ENTRYPOINT ["java", "-jar", "optimize-weight-value-services-service.jar"]
